export const SITE = {
  name: 'Rajeev Verma',
  tagline: 'Freelance Flutter, MERN & AI Developer',
  email: 'rajeevverma4577@gmail.com',
  linkedin: 'https://www.linkedin.com/in/rajeev-verma7276/',
  github: 'https://github.com/Rajeevgithu',
  instagram: 'https://www.instagram.com/rajeev__verma_04/',
  twitter: 'https://x.com/RajeevVerma45',
  location: 'Mumbai, India',
  domain: 'https://rajeevverma-portfolio.com',
  bookingUrl: 'https://cal.com',
  resumePath: '/RajeevVerma_Resume.pdf',
  formspreeEndpoint: 'https://formspree.io/f/mpwrbnrk',
  responseTime: '24 hours',
  availability: 'Open for freelance projects',
  freelanceHours: '10–15 hrs/week for freelance',
  currentRole: 'Full Stack Developer @ Dharmik Vibes',
  currentCompany: 'Dharmik Vibes',
  projectCount: 10,
  technologyCount: 35,
  experienceLabel: '1+ Years Experience',
};
